### PR TITLE
Cartesian Points Class + Functions for it

### PR DESCRIPTION
**Pull request by linchuandai**
Added a points class for easier usage throughout the program.

### CODE REVIEW

**Comment by Wesley-Fisher** [comment]
I think the failing tests/build can be fixed with an update/merge from dev

**Comment by linchuandai** [comment]
> I think the failing tests/build can be fixed with an update/merge from dev

**Comment by linchuandai** [comment]
> I think the failing tests/build can be fixed with an update/merge from dev

Merged and fixed.

**Review by amaarquadri — CHANGES_REQUESTED** [review]
The points_helper.py file should be moved somewhere within the src directory of the catkin workspace, not at the root of the repo. Not sure where exactly the best place is. Maybe we should create a package for miscellaneous helper classes?

**Pull request closed without merging**
